image: Ubuntu2004  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - main  # ветка git

build: off  # будем использовать свой скрипт сборки

build_script:
  # Запускаем автотесты
  # Для проектов на базе Selenide необходимо добавить параметр для запуска браузера
  # в headless режиме -Dselenide.headless=true, параметр --info должен остаться
  - ./gradlew test --info